### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by akosnad** [rust-osdev/vga#16]
On the latest nightly `1.49.0-nightly (ffa2e7ae8 2020-10-24)` the dependency `x86_64 ^0.11.0` is causing the issue. One of the build-time errors is, for example:
```
error[E0658]: mutable references are not allowed in constant functions
   --> C:\Users\xxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\x86_64-0.11.8\src\structures\idt.rs:402:30
    |
402 |                 interrupts: [Entry::missing(); 256 - 32],
    |                              ^^^^^^^^^^^^^^^^
    |
    = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
    = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable
```

I think this is due to the new rust feature `const_mut_refs` and the issue has been fixed in `x86_64 ^0.12`. A dependency bump would be great :)

**Comment by RKennedy9064** [comment]
@akosnad I've been meaning to fix this, but needed to replace a hard drive and reinstall everything before I could. I updated the versions on develop #17. Can you try building from that branch and if it fixes your issue I'll merge it in and release a new version.

**Comment by akosnad** [comment]
I built it from the dev branch and everything works as expected for me. Awesome, thanks! :)
