### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by Pollux3737** [rust-osdev/vga#19]
Hello,

I was trying to compile a file using vga as a dependance. However, it uses an out of date version of the x86_64 crate (v0.12.4 while v0.13.2 is available as of writing).
With the new nightly versions, the old x86_64 refuses to compile. I therefore suggest that the dependency for x86_64 is updated.

**Comment by RKennedy9064** [comment]
Thanks for the update to fix the build. I also updated the workflow and published a new crate, so everything should build correctly now. Let me know if the new version works for you and I'll close this issue.

**Comment by Pollux3737** [comment]
Works like a charm, thanks a lot !
